name: Run
on: [push]

jobs:
  macOS-latest:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Clone FastDeploy
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'PaddlePaddle'
          repository: 'FastDeploy'

      - name: Build FastDeploy
        working-directory: ./FastDeploy
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_ORT_BACKEND=ON -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
          make -j12
          make install
          ls -l

      - name: Copy
        run: |
          cp -r ./FastDeploy/build/compiled_fastdeploy_sdk ./compiled_fastdeploy_sdk
          rm -rf FastDeploy
          ls -l
#
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Build
#        run: |
#          npm install
#          npx gulp
#
#      - name: Run
#        run: node index.js
