name: Run
on: [push]

jobs:
  macOS-latest:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npx gulp

      - name: Run
        run: node index.js
